### ISSUE TITLE
last section crashing to atmosphere error screen

### ISSUE THREAD

**Issue by JonJaded** [FuryBaguette/AmiiSwap#11]
Here are the details -
Firmware: 8.0.1
Error Code: 2168-002 (0x4a8)

[This is my settings.txt configuration when it crashes.](https://pastebin.com/QvDE78iG)

But the crash upon selecting the final section will stop if I move my "[Super Smash Bros]" section to the very bottom of the config.

[My settings.txt config when I move my Smash section to the bottom.](https://pastebin.com/9esUdVWf)

I can provide my emuiibo directory if you need me to for further analysis. I also attached my crash report.

[crash_reports.zip](https://github.com/FuryBaguette/AmiiSwap/files/3169232/crash_reports.zip)

**Comment by FuryBaguette** [comment]
@JonJaded I found out why it crashes.
There needs to be a newline after each line, even the last one. What happens here is that since there is no newline at the end, the only amiibo that is in the game doesn't get picked up, so the amiibo list for this game is empty. This should not make it crash for next release.
Please add a newline at the end to avoid the crash and close the issue if that fixed it.

**Comment by FuryBaguette** [comment]
This should be fixed with 5e14d7cc6c8c3ce17f1b014ae4b81a6db071706e
