### ISSUE TITLE
i don't understand

### ISSUE THREAD

**Issue by chronoss09** [FuryBaguette/AmiiSwap#2]
Amiibo use : titles/0100000000000352
AmiiSwap use : titles/0100000000000052

Who is the best or the wrong folder ?

**Comment by FuryBaguette** [comment]
> Amiibo use : titles/0100000000000352
> AmiiSwap use : titles/0100000000000052
> 
> Who is the best or the wrong folder ?

If you're using Emuiibo the right folder is ...352
If you're using switch-nfp-mitm the right folder is ...52

I suggest you to use [Emuiibo](https://github.com/XorTroll/emuiibo) since it's more stable and will get updates. Read the readme on the emuiibo's github page to set it up, then you can just download AmiiSwap.nro and put it in the switch folder and it will work.
